version: "3.8"
services:
  front:
    image: nginx
    volumes: 
    - C:\Users\andre\Desktop\Temp\Corsi\Avalon\Zecca\sessione-2\web:/usr/share/nginx/html:ro
    - C:\Users\andre\Desktop\Temp\Corsi\Avalon\Zecca\sessione-2\conf\nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - 8080:80
    networks:
    - my_net    
  pma:
    image: phpmyadmin
    environment: 
      MYSQL_ROOT_PASSWORD: passw0rd
    links:
    - mydb:db
    networks:
    - my_net
  mydb:
    image: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: passw0rd
    volumes: 
    - mysql_data:/var/lib/mysql 
    networks:
    - my_net         
volumes: 
  mysql_data:
  web_static:
networks:
  my_net: