version: "3.8"
services:
    db01:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: passw0rd
        ports:
        - 3306:3306
        volumes:
        - mysql_data:/var/lib/mysql
volumes:
    mysql_data:
        driver: local
        driver_opts:
              o: bind
              type: none
              device: /home/andrea/db