version: "3.8"
services:
  front:
    image: nginx
    volumes: 
    - /home/andrea/ipzs-2021-sessione-2/web:/usr/share/nginx/html:ro
    - /home/andrea/ipzs-2021-sessione-2/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - 8080:80
    networks:
    - my_net
  api:
    image: ipzs/api-corso:latest
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
    - my_net
networks:
  my_net:
