version: "3.8"
services:
  front:
    image: nginx
    volumes: 
    - C:\Users\andre\Desktop\Temp\Corsi\Avalon\Zecca\sessione-2\web:/usr/share/nginx/html:ro
    - C:\Users\andre\Desktop\Temp\Corsi\Avalon\Zecca\sessione-2\conf\nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - 8080:80
    networks:
    - my_net
  api:
    image: ipzs/api-corso:latest
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
    - my_net
networks:
  my_net:
